// Scans characters/<hero>/{board,leaflet,cards}/ and characters/common/ for image files,
// and bundles them + the hero.json/common-cards.json template data into a single generated
// JS file the static verify page can load without a server (no fetch() of local files needed).
import fs from 'fs';
import path from 'path';

const IMG_EXT = /\.(png|jpe?g|webp|gif)$/i;

function listImages(relDir) {
  if (!fs.existsSync(relDir)) return [];
  return fs.readdirSync(relDir)
    .filter(f => IMG_EXT.test(f))
    .sort()
    .map(f => path.posix.join(relDir, f));
}

function readJson(relPath) {
  return JSON.parse(fs.readFileSync(relPath, 'utf8'));
}

const heroes = {
  hh: {
    board: listImages('../characters/headless_horseman/board'),
    leaflet: listImages('../characters/headless_horseman/leaflet'),
    cards: listImages('../characters/headless_horseman/cards'),
    data: readJson('src/sim/data/characters/hh/hero.json'),
  },
  bw: {
    board: listImages('../characters/Black_Widow/board'),
    leaflet: listImages('../characters/Black_Widow/leaflet'),
    cards: listImages('../characters/Black_Widow/cards'),
    data: readJson('src/sim/data/characters/bw/hero.json'),
  },
  fm: {
    board: listImages('../characters/forge_master/board'),
    leaflet: listImages('../characters/forge_master/leaflet'),
    cards: listImages('../characters/forge_master/cards'),
    data: readJson('src/sim/data/characters/fm/hero.json'),
  },
};

const common = {
  images: listImages('../characters/common'),
  data: readJson('src/sim/data/common-cards.json'),
};

const out = `// GENERATED by engine-ts/gen-assets.mjs — do not edit by hand. Re-run \`npm run build\`.
window.CHARACTER_ASSETS = ${JSON.stringify({ heroes, common }, null, 2)};
`;

fs.writeFileSync('../static/character-assets.generated.js', out);
console.log('Generated static/character-assets.generated.js');
