GRIM_PURSUIT_AVG_DMG = 1.66
CARD_DRAW_VALUE = 2.0
CP_TO_DMG_EQUIV = 1.5

SPECTRAL_ASSAULT_BASE = 8.0
SPECTRAL_ASSAULT_PER_DREADFUL = 1.5

DREADFUL_CHARGE_VALUE = 15.0
DREADFUL_CHARGE_DREADFUL_GIVEN = 4

CLEAVE_3A = 4.0
CLEAVE_4A = 5.0
CLEAVE_5A = 7.0

REAP_UNDEFENDABLE = 3.0
REAP_DREADFUL_GIVEN = 2

RIDE_DOWN_BASE = 6.0

SOW_SMALL_DMG = 7.0
SOW_SMALL_DREADFUL = 1
SOW_LARGE_DMG = 9.0
SOW_LARGE_DREADFUL = 2

HORRIFY_BASE_UNDEFENDABLE = 6.0
HORRIFY_DREADFUL_GIVEN = 3

WHIFF_PURSUIT_TOKENS = 1
